// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSTIL48ksb8XqldCezZ9IRsUHSoHN2M0s',
    appId: '1:469000873912:web:a85b89be076a91bef2514d',
    messagingSenderId: '469000873912',
    projectId: 'study-notes-1abf9',
    authDomain: 'study-notes-1abf9.firebaseapp.com',
    storageBucket: 'study-notes-1abf9.appspot.com',
    measurementId: 'G-L5SK0ME929',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0TJTUkuJ0NCcV0LPfeePYUSqhIhKG5xs',
    appId: '1:469000873912:android:cb9b735f34743c0bf2514d',
    messagingSenderId: '469000873912',
    projectId: 'study-notes-1abf9',
    storageBucket: 'study-notes-1abf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAowVPtjMf3NATxLxLkZ7p7AgrUn_CFiJo',
    appId: '1:469000873912:ios:59c4cd5149b4da84f2514d',
    messagingSenderId: '469000873912',
    projectId: 'study-notes-1abf9',
    storageBucket: 'study-notes-1abf9.appspot.com',
    iosClientId: '469000873912-bbh0g4j717jg7632n7jeetd91g74q594.apps.googleusercontent.com',
    iosBundleId: 'com.example.makequiz',
  );
}
