// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQwF94MDhRnsplLjTcfUmjUF0_qSeuFdA',
    appId: '1:1021096788999:web:20e8dfd06724f58b49d6a2',
    messagingSenderId: '1021096788999',
    projectId: 'startup-9d293',
    authDomain: 'startup-9d293.firebaseapp.com',
    storageBucket: 'startup-9d293.appspot.com',
    measurementId: 'G-YM1S3B7SMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDimVntBMU0-ilf7-0ehthzBfsepagIK7E',
    appId: '1:1021096788999:android:4b56fc54b5f2b07949d6a2',
    messagingSenderId: '1021096788999',
    projectId: 'startup-9d293',
    storageBucket: 'startup-9d293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6hSaOAT6rKxQ9awwFYc-U33b5iV5gmuo',
    appId: '1:1021096788999:ios:87f17b21aadc544c49d6a2',
    messagingSenderId: '1021096788999',
    projectId: 'startup-9d293',
    storageBucket: 'startup-9d293.appspot.com',
    iosClientId: '1021096788999-35ptadmucd5jg2tmjrhrs5kf96r1ubs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.makequiz',
  );
}
